### ISSUE TITLE
Container never sends 408 Request Timeout for OPTIONS that never receives a response

### ISSUE THREAD

**Issue by gvagenas** [Mobicents/sip-servlets#91]
This is a problem we have at Restcomm with the registration of the clients - https://github.com/Mobicents/RestComm/issues/27

Restcomm sends an OPTIONS request to every registered client every 60 seconds as a keepalive mechanism. For the cases where the client is abruptly stopped and cannot respond to the OPTIONS request, container never sends a 408 and as a result the application (Restcomm) cannot be notified about the failed OPTIONS requests and remove the registration.

To reproduce this bug I used SFLPhone which consists of two parts, the daemon that is the sip stack of the client and responsible for the SIP request/responses and the GTK GUI. 

So using SFLPhone I registered and Restcomm after 60 secs sent the first OPTIONS request the SFLPhone daemon responded with 200 OK.

Next I killed SFLPhone daemon so the client now cannot response to the OPTIONS requests. Note that if I exit the client it un-register so wont possible to reproduce the issue.

At the logs attached the SFLPhone daemon is killed after 12:29:52,967 as you see bellow:

```
12:29:52,967 DEBUG [org.mobicents.servlet.sip.core.SipApplicationDispatcherImpl] (MSS-Executor-Thread-2) sip session already invalidated(58511781_2f7182de_57a5b08a_84a12115;b1ce952989edb73130d16481c2d9c3e6@192.168.1.151;84a12115;RestComm)

***** Killed SFLPhone daemon *****

12:30:37,476 DEBUG [org.apache.catalina.session] (ContainerBackgroundProcessor[StandardEngine[jboss.web]]) Start expire sessions StandardManager at 1447237837476 sessioncount 0
```

Later when Restcomm sends OPTIONS request again, there is no 408 response from the container but instead I can only see re-transmissions of the request and finally invalidation of the sessions.

Tested with Mobicents Sip Servlets 3.1.640

Full log in DEBUG log level: https://gist.github.com/gvagenas/7f0fc3a76429402385f6

**Comment by deruelle** [comment]
I created a non regression test and couldn't reproduce. Looking at the logs I see the 408 is correctly generated, see below. Can you check if Restcomm handles the doErrorResponse and 408 correctly ?
 
`12:31:20,086 DEBUG [org.mobicents.servlet.sip.core.session.SipManagerDelegate] (MSS-Executor-Thread-3) trying to find sip application session with key 6cb2c273;RestComm
12:31:20,086 DEBUG [org.mobicents.servlet.sip.core.session.SipManagerDelegate] (MSS-Executor-Thread-3) Totag 93015337_2f7182de_57a5b08a_6cb2c273 currentKeyToTag 93015337_2f7182de_57a5b08a_6cb2c273
12:31:20,086 DEBUG [org.mobicents.servlet.sip.core.dispatchers.MessageDispatcher] (MSS-Executor-Thread-3) Dispatching response SIP/2.0 408 Request timeout
To: <sip:bob@192.168.1.151:5960>;tag=93015337_2f7182de_57a5b08a_6cb2c273
Via: SIP/2.0/UDP 192.168.1.151:5080;branch=z9hG4bK6cb2c273_57a5b08a_b3650d5e-f23f-4451-af3b-45523dc2c4bc
CSeq: 1 OPTIONS
Call-ID: b8d200e90b8a2f3013a23d761dfd9e48@192.168.1.151
From: <sip:restcomm@192.168.1.151>;tag=54917207_2f7182de_57a5b08a_6cb2c273
Server: Mobicents Restcomm 7.4.0.740
Content-Length: 0

 to following App/servlet => RestComm/UserAgentManager on following sip session (54917207_2f7182de_57a5b08a_6cb2c273;b8d200e90b8a2f3013a23d761dfd9e48@192.168.1.151;6cb2c273;RestComm)
12:31:20,087 DEBUG [org.mobicents.servlet.sip.core.session.SipSessionImpl] (MSS-Executor-Thread-3) resetting the to tag since a response to a non dialog creating and terminating method has been received for non proxy session with no dialog in state INITIAL
12:31:20,087 DEBUG [org.mobicents.servlet.sip.core.session.SipSessionImpl] (MSS-Executor-Thread-3) Setting SipSession (54917207_2f7182de_57a5b08a_6cb2c273;b8d200e90b8a2f3013a23d761dfd9e48@192.168.1.151;6cb2c273;RestComm) for response 408 to a non dialog creating or terminating request OPTIONS in state INITIAL to ReadyToInvalidate=true`
